# Generated by Django 5.2.8 on 2025-11-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saludos_app', '0003_autor_etiqueta_articulo_autor_articulo_etiquetas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('notificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_notificacion', models.CharField(max_length=100)),
                ('fecha_notificacion', models.DateField()),
                ('categoria_notificacion', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asunto', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
